# Generated by Django 4.2.19 on 2025-02-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_read', 'Can read data'), ('can_edit', 'Can edit data'), ('can_manage_users', 'Can activate/deactivate and delete users')]},
        ),
    ]
