# Generated by Django 5.1.7 on 2025-03-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0003_alter_userprofile_options_approvalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
