# Generated by Django 5.1.7 on 2025-03-19 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0005_alter_userprofile_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETDForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_number', models.CharField(max_length=100)),
                ('degree_type', models.CharField(choices=[('masters', 'Master'), ('doctorate', 'Doctorate')], max_length=20)),
                ('graduation_date', models.CharField(max_length=50)),
                ('request_type', models.CharField(choices=[('first_extension', 'First Embargo Extension'), ('additional_extension', 'Additional Embargo Extension'), ('full_hold', 'Full Record Hold'), ('other', 'Other')], max_length=20)),
                ('justification', models.TextField()),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='generated_forms/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('returned', 'Returned'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etd_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
