# Generated by Django 5.1.6 on 2025-03-20 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0006_etdform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('degree_type', models.CharField(max_length=20)),
                ('graduation_date', models.CharField(max_length=10)),
                ('request_type', models.CharField(max_length=50)),
                ('justification', models.TextField()),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=100)),
                ('degree_plan', models.CharField(max_length=100)),
                ('mailing_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('withdrawal_term', models.CharField(max_length=20)),
                ('last_attendance_date', models.DateField()),
                ('withdrawal_reason', models.TextField()),
                ('supporting_docs', models.FileField(blank=True, null=True, upload_to='withdrawal_docs/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
