# Generated by Django 5.1.6 on 2025-03-20 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0007_thesisrequest_withdrawalrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesisrequest',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='thesisrequest',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='thesisrequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='thesisrequest',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='supporting_docs',
        ),
        migrations.AddField(
            model_name='thesisrequest',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='generated_pdfs/'),
        ),
        migrations.AlterField(
            model_name='thesisrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='thesisrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
