# Generated by Django 5.1.6 on 2025-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0008_rename_submitted_at_thesisrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='thesisrequest',
            name='justification',
            field=models.TextField(default='No justification provided'),
        ),
        migrations.AddField(
            model_name='thesisrequest',
            name='request_type',
            field=models.CharField(default='Unknown Request', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='campus_housing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='financial_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='gi_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='student_initial',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='uh_health_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='visa_holder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thesisrequest',
            name='degree_type',
            field=models.CharField(choices=[('Master', 'Master'), ('Doctorate', 'Doctorate')], default='Master', max_length=20),
        ),
        migrations.AlterField(
            model_name='thesisrequest',
            name='graduation_date',
            field=models.CharField(default='MM/YYYY', max_length=10),
        ),
        migrations.AlterField(
            model_name='thesisrequest',
            name='student_id',
            field=models.CharField(default='0000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='college',
            field=models.CharField(default='Unknown College', max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='degree_plan',
            field=models.CharField(default='Unknown Degree Plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='last_attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='student_id',
            field=models.CharField(default='0000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='withdrawal_reason',
            field=models.TextField(default='No reason provided'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='withdrawal_term',
            field=models.CharField(default='Spring 2025', max_length=20),
        ),
    ]
