# Generated by Django 5.1.6 on 2025-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0009_remove_withdrawalrequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='address',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='state',
            field=models.CharField(default='Unknown State', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='street_address',
            field=models.CharField(default='No address provided', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='zipcode',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
