# Generated by Django 5.1.6 on 2025-04-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0013_alter_thesisrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedCourseLoadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='0000000', max_length=7)),
                ('reason', models.CharField(choices=[('academic_difficulty', 'Academic Difficulty'), ('medical_reason', 'Medical Reason'), ('final_semester_non_thesis', 'Final Semester - Non-Thesis Track'), ('final_semester_thesis', 'Final Semester - Thesis/Dissertation Track')], max_length=40)),
                ('academic_difficulty_types', models.JSONField(blank=True, null=True)),
                ('medical_letter_attached', models.BooleanField(default=False)),
                ('final_semester_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=10)),
                ('semester_year', models.PositiveIntegerField(default=2025)),
                ('courses_to_drop', models.CharField(default='', help_text='Comma-separated list of course numbers', max_length=255)),
                ('total_credit_hours_after_drop', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('returned', 'Returned'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='generated_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcl_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
