# Generated by Django 5.1.7 on 2025-04-15 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0015_rename_academic_difficulty_types_reducedcourseloadrequest_iai_reasons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='0000000', max_length=7)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('phone', models.CharField(default='000-000-0000', max_length=15)),
                ('career', models.CharField(default='GRAD', max_length=20)),
                ('program', models.CharField(default='Unknown Program', max_length=20)),
                ('plan_code', models.CharField(default='Unknown Plan', max_length=20)),
                ('term', models.CharField(default='Fall', max_length=10)),
                ('year', models.CharField(default='2025', max_length=4)),
                ('purpose', models.CharField(default='10', max_length=2)),
                ('other_purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_state_zip', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_start_term', models.CharField(blank=True, max_length=10, null=True)),
                ('transfer_start_year', models.CharField(blank=True, max_length=4, null=True)),
                ('transfer_end_term', models.CharField(blank=True, max_length=10, null=True)),
                ('transfer_end_year', models.CharField(blank=True, max_length=4, null=True)),
                ('credit_description', models.TextField(blank=True, null=True)),
                ('hours_transferred', models.CharField(blank=True, max_length=5, null=True)),
                ('requested_hours', models.CharField(blank=True, max_length=5, null=True)),
                ('explanation', models.TextField(default='No explanation provided')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Review'), ('Returned', 'Returned for Revision'), ('Approved', 'Approved')], default='Draft', max_length=20)),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='generated_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
