# Generated by Django 5.1.6 on 2025-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0016_petitionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reducedcourseloadrequest',
            name='current_semester',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], default='fall', max_length=10),
        ),
        migrations.AddField(
            model_name='reducedcourseloadrequest',
            name='current_year',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='reducedcourseloadrequest',
            name='semester_year',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
