# Generated by Django 5.1.6 on 2025-04-17 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0017_reducedcourseloadrequest_current_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cougar_id',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Cougar ID must be exactly 7 digits', regex='^\\d{7}$')]),
        ),
    ]
