# Generated by Django 5.1.6 on 2025-04-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0018_userprofile_cougar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, choices=[('architecture', 'Gerald D. Hines College of Architecture and Design'), ('arts', 'Kathrine G. McGovern College of the Arts'), ('business', 'C.T. Bauer College of Business'), ('education', 'College of Education'), ('engineering', 'Cullen College of Engineering'), ('technology', 'Technology Division at the Cullen College of Engineering'), ('liberal_arts', 'College of Liberal Arts and Social Sciences'), ('nsm', 'College of Natural Sciences and Mathematics'), ('nursing', 'Andy and Barbara Gessner College of Nursing'), ('medicine', 'Tilman J. Fertitta Family College of Medicine'), ('optometry', 'College of Optometry'), ('pharmacy', 'College of Pharmacy'), ('hospitality', 'Conrad N. Hilton College of Global Hospitality Leadership'), ('law', 'UH Law Center'), ('social_work', 'Graduate College of Social Work'), ('public_affairs', 'Hobby School of Public Affairs'), ('honors', 'The Honors College')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
