# Generated by Django 5.1.6 on 2025-04-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_mgmt_app', '0019_userprofile_academic_level_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='static/images/default_profile.png', upload_to='profile_pictures/'),
        ),
    ]
